In [ ]:
!pip install numba
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

/usr/local/cuda-10.0/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/libdevice
/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so
/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so


In [7]:
from numba import cuda
from numba import vectorize
import math
import numpy as np

# This is square root of 2*pi
SQRT_TWOPI = np.float32(math.sqrt(2 * math.pi))

# Leverage CUDA to conduct repetitive operations
@vectorize(['float32(float32, float32, float32)'], target='cuda')

# Define Gaussian Function
def gaussian(x, x0, sigma):
    return math.exp(-((x - x0) / sigma)**2 / 2) / (SQRT_TWOPI * sigma)

# Generate Numbers
x = np.linspace(-3, 3, 10000, dtype=np.float32)

# 1D Distribution
g = gaussian(x, 0, 1)  # 1D result
print(g)

# 2D Distribution
x2d = x.reshape((100,100))
g2d = gaussian(x2d, 0, 1) # 2D result
print(g2d)

[0.00443185 0.00443983 0.00444783 ... 0.00444783 0.00443983 0.00443185]
[[0.00443185 0.00443983 0.00444783 ... 0.00526847 0.00527778 0.0052871 ]
 [0.00529644 0.00530579 0.00531515 ... 0.00627432 0.00628518 0.00629605]
 [0.00630695 0.00631785 0.00632877 ... 0.00744535 0.00745797 0.0074706 ]
 ...
 [0.0074706  0.00745797 0.00744535 ... 0.00632877 0.00631785 0.00630695]
 [0.00629605 0.00628518 0.00627432 ... 0.00531515 0.00530579 0.00529644]
 [0.0052871  0.00527778 0.00526847 ... 0.00444783 0.00443983 0.00443185]]
